# Site settings
title: You Blog                     #你博客的标题
header-img: static/longzhou.jpg   #显示在首页的背景图片
email: wszlong@gmail.com    
url: "https://long-zhou.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
